### ISSUE TITLE
How to set a custom tuner_path ? 

### ISSUE THREAD

**Issue by la-cruche** [awslabs/syne-tune#107]
Hi,

how to set a custom `tuner_path`?

I'm launching long-running experiments on remote SageMaker jobs, and I'd like to set the tuner metadata path to `/opt/ml/checkpoints` (local path on those transient VMs), to get the metadata sent to s3 upon updates

**Comment by geoalgo** [comment]
Hi Olivier,

This should happen already automatically for remote tuning. Syne Tune detects when you are on SageMaker and writes into `/opt/ml/checkpoints` which is checkpointed into `s3://{s3_bucket}/syne-tune/{tuner-name}/`.

There is this part that explains it in our readme, let us know if you have any follow-up questions.

> Output of a tuning job when running tuning on SageMaker. When the tuning runs remotely on SageMaker, the results are stored at a regular cadence to s3://{s3_bucket}/syne-tune/{tuner-name}/, where s3_bucket can be configured (defaults to default_bucket of the session). For instance, if the above experiment is run remotely, the following path is used for checkpointing results and states:

Relevant code:
* https://github.com/awslabs/syne-tune/blob/main/syne_tune/remote/remote_launcher.py#L187
* https://github.com/awslabs/syne-tune/blob/main/syne_tune/util.py#L64
