### ISSUE TITLE
Cannot serialize sp.finrange

### ISSUE THREAD

**Issue by talesa** [awslabs/syne-tune#162]
Hello! 
Serialization of the `syne_tune.search_space.finrange` is failing - if we define the sp.finrange in the config_space, the Blackbox serialization tests fail:
https://github.com/talesa/syne-tune/blob/blackbox-serialization-with-finrange-bug/tst/blackbox_repository/test_blackbox.py#L21-L24

**Comment by mseeger** [comment]
FiniteRange does not have a sampler. This to_dict and from_dict has to be fixed. I can do that.

**Comment by mseeger** [comment]
This is harder than I thought. Again, this to_dict and from_dict is making assumptions that are just not true for general classes. FiniteRange has a member _uniform_int, which is not JSON-serializable.

**Comment by talesa** [comment]
Thank you Matthias!

**Comment by mseeger** [comment]
This fix has been merged now
