### ISSUE TITLE
list_experiments failing when no experiments are available

### ISSUE THREAD

**Issue by 610v4nn1** [awslabs/syne-tune#190]
I accidentally ran ```list_exp = list_experiments()``` using a different AWS account and noticed that the function fails with ```EmptyDataError: No columns to parse from file``` when there are no experiments available.

**Comment by geoalgo** [comment]
I could not reproduce this error. Running this method works fine even with an empty experiment folder. It seems that the error may be caused by another part (list_experiments yields an iterator built over file). If you face the issue again, could you post a minimum reproducible example?
