### ISSUE TITLE
list_experiments does not list the experiments results available locally

### ISSUE THREAD

**Issue by 610v4nn1** [awslabs/syne-tune#191]
I have a long list of results available in my local SyneTune folder (```~/syne-tune/```) and list_experiments doesn't add them to the list. The experiments are not stored in an S3 bucket of my property but they are copied from a different location to the local filesystem.

**Comment by geoalgo** [comment]
Only the experiments that have `results.csv.zip` and `metadata.json` are listed by `list_experiments`. Can you confirm that those files are present in your local folder?

For instance, you should have a structure like this:
```bash
tree ~/syne-tune

/Users/dsalina/syne-tune/
├── ASHA-0-fcnet-naval-2022-03-16-10-44-17-218
│   ├── metadata.json
│   └── results.csv.zip
...
```

**Comment by 610v4nn1** [comment]
I did some clean up the structure is slightly different but I don't think that has an impact.

```
└── XYZ-experiment-2022-02-28-11-52-43-791
    ├── 0
    │   ├── config.json
    │   ├── end
    │   ├── std.err
    │   └── std.out
    ├── metadata.json
    ├── results.csv.zip
    └── tuner.dill
```

... but there are folders where the results file is missing

```
$ ls -R ~/syne-tune/ | grep results.csv | wc -l
     955
$ ls  ~/syne-tune/ |  wc -l
     960
```
and the loading is failing with the following error

`EmptyDataError: No columns to parse from file`

My initial description is not accurate and the problem is probably related to a few missing results in the local folder which make `list_experiments` fail.
