### ISSUE TITLE
TransferLearningTaskEvaluations.top_k_hyperparameter_configurations does not respect config_space

### ISSUE THREAD

**Issue by wistuba** [awslabs/syne-tune#198]
Methods that will use top k candidates will therefore use out of config space configs which will raise in error. Restrict the feasible candidates for this function to everything within the config_space.

**Comment by mseeger** [comment]
In fact, we have introduced this active_config_space parameter in HyperparameterRanges for exactly this reason, namely you want to warmstart from data whose configs lie out of your config_space. There is even some code to determine ranges and active ranges from a desired config space and transfer data, but it is in another package. We could move this code to ST if this is needed now.

**Comment by wistuba** [comment]
Not sure I understand you correctly but TransferLearningTaskEvaluations allows you to store any data, no matter the config_space. However, the function `top_k_hyperparameter_configurations` should only return configs within the config_space which it doesn't do right now. Therefore, any transfer learning method that uses this function and simply suggest it will raise an exception. It's not an urgent task, I just want to keep track of it so I won't forget.

**Comment by mseeger** [comment]
Sure, but if we want to fix this, the basic parts are already there.
Essentially, you need to allow configs of the transfer data to lie outside the ranges of your current config_space.
