### ISSUE TITLE
Warning: Python 3.6

### ISSUE THREAD

**Issue by austinmw** [awslabs/syne-tune#243]
Hi, I receive this warning using the docker image:

> PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/

Since this is only a couple of weeks away it might be a good idea to update the Dockerfile to Python 3.7 now.

**Comment by geoalgo** [comment]
Thanks for catching this, we sent a fix that should be available shortly.
