### ISSUE TITLE
ExperimentResult plot warning

### ISSUE THREAD

**Issue by austinmw** [awslabs/syne-tune#251]
Hi, with recent versions of matplotlib, `ExperimentResult.plot()` gives me the warning:

> WARNING:matplotlib.legend:No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

**Comment by Valavanca** [comment]
I can take it but need some clarification. I would display all metrics not just the first one. In that case the y-axis would be called 'value' or something like that + a legend entry for each metric. 
Otherwise, the legend could just be removed since the y-axis already has the name of the metric.

**Comment by mseeger** [comment]
Sounds reasonable. Thanks for offering help!

**Comment by wistuba** [comment]
No longer plotting all metrics since their modes are not clear.
