### ISSUE TITLE
make QuantileBasedSurrogateSearcher import in baselines optional

### ISSUE THREAD

**Issue by aaronkl** [awslabs/syne-tune#315]
Right now importing `syne_tune.optimizer.baselines` fails when only core dependencies are installed because it imports QuantileBasedSurrogateSearcher, which in turn requires additional dependencies, such as XGBoost or sklearn. I would suggest to make it's import optional to avoid exceptions.

**Comment by mseeger** [comment]
Can you try to do it? I am all for conditional imports. Code should not fail just for being present, it should only fail if the user tries to execute it. This should be the normal for code with extensive dependencies.

**Comment by mseeger** [comment]
I can take this, I need to improve conditional imports anyway towards AutoGluon integration

**Comment by mseeger** [comment]
Fixed by #320
