### ISSUE TITLE
Config_space for full pipeline optimization

### ISSUE THREAD

**Issue by Bilgecelik** [awslabs/syne-tune#316]
Hi, would it be possible to direct the config_space search for a conditional set formation so it can create a multi-step pipeline? 
Something that will limit activation of invalid pipelines from alg+hp config variables.

**Comment by mseeger** [comment]
Do you want to give it a try?

I suppose you ask for conditional search spaces, where the value of one HP determines the range for another, or even whether the other HP exists. This is something we do not support out of the box.

One reason is we want to support model-based HPO (e.g., Bayesian optimization), which is difficult to do with conditional spaces. If we only went for random search or simple evolutionary search, conditional spaces are not a problem at all, it just has not been high on our agenda.

**Comment by mseeger** [comment]
@Bilgecelik Could you be more specific here in what is needed? Proper support for conditional search spaces is a big item that we will not be able to do quickly, but you may want to give it a try.

**Comment by Bilgecelik** [comment]
Yes of course, I want to use syne-tune for a full pipeline optimization including a multi-step pipeline and multiple learners. So it extends the search space from a single learner's hyperparameters. The question was can I force syne-tune to select hyperparameters in a way that makes a sensible full pipeline in order to help the search. But currently I am flattening the search space and forcing selection of classifiers with choice variables. Similar to Autosklearn search space. It would be more efficient if Syne-tune had an internal check to avoid searching infeasible parts of search space though.

**Comment by mseeger** [comment]
OK, nice. Would be interested to see more of this project once it works.

As I said, you can do this by overloading our RandomSearcher with something that samples with rejection, or more efficiently, knows the structure and samples accordingly. We have no plans yet to support this generically, but if you come up with a good implementation of this, we can merge it in.
