### ISSUE TITLE
BlackboxSurrogate returns inconsistent values for LCBench blackbox

### ISSUE THREAD

**Issue by mseeger** [awslabs/syne-tune#319]
This is a follow-up issue for #304.

**Comment by mseeger** [comment]
Debug code here: https://github.com/awslabs/syne-tune/blob/debug_martin/syne_tune/blackbox_repository/simulated_tabular_backend.py#L156
And here: https://github.com/awslabs/syne-tune/blob/debug_martin/syne_tune/blackbox_repository/utils.py#L54

**Comment by mseeger** [comment]
If I then run python benchmarking/nursery/benchmark_automl/benchmark_main.py --num_seeds 1 --method ASHA --benchmark lcbench-airlines

I get output like this:

Index(['val_accuracy', 'time'], dtype='object') {'val_accuracy': 54.633484, 'time': 33.52457, 'epoch': 1} {'val_accuracy': 54.633484, 'time': 33.52457, 'epoch': 2} {'val_accuracy': 54.633484, 'time': 33.52457, 'epoch': 3} {'val_accuracy': 55.08092, 'time': 50.357838, 'epoch': 4} {'val_accuracy': 55.907024, 'time': 67.25511, 'epoch': 5} {'val_accuracy': 56.68802, 'time': 84.19331, 'epoch': 6} {'val_accuracy': 57.218803, 'time': 101.09334, 'epoch': 7} {'val_accuracy': 57.582386, 'time': 118.04459, 'epoch': 8} {'val_accuracy': 57.81063, 'time': 135.03284, 'epoch': 9} {'val_accuracy': 57.95385, 'time': 152.08, 'epoch': 10} {'val_accuracy': 58.067047, 'time': 169.16852, 'epoch': 11} {'val_accuracy': 58.141846, 'time': 186.28845, 'epoch': 12} {'val_accuracy': 58.18696, 'time': 203.40231, 'epoch': 13} {'val_accuracy': 58.220665, 'time': 220.46123, 'epoch': 14} {'val_accuracy': 58.24464, 'time': 237.45142, 'epoch': 15} {'val_accuracy': 58.243977, 'time': 254.37263, 'epoch': 16} {'val_accuracy': 58.246155, 'time': 271.27945, 'epoch': 17} {'val_accuracy': 58.26594, 'time': 288.19318, 'epoch': 18} {'val_accuracy': 58.282715, 'time': 305.1667, 'epoch': 19} {'val_accuracy': 58.286236, 'time': 322.18546, 'epoch': 20} {'val_accuracy': 58.30233, 'time': 339.26794, 'epoch': 21} {'val_accuracy': 58.31726, 'time': 356.34616, 'epoch': 22} {'val_accuracy': 58.31894, 'time': 373.41287, 'epoch': 23} {'val_accuracy': 58.321625, 'time': 390.44696, 'epoch': 24} {'val_accuracy': 58.326984, 'time': 407.4664, 'epoch': 25} {'val_accuracy': 58.333534, 'time': 424.4817, 'epoch': 26} {'val_accuracy': 58.336884, 'time': 441.51205, 'epoch': 27} {'val_accuracy': 58.336548, 'time': 458.55728, 'epoch': 28} {'val_accuracy': 58.336548, 'time': 475.6127, 'epoch': 29} {'val_accuracy': 58.338898, 'time': 492.60458, 'epoch': 30} {'val_accuracy': 58.338726, 'time': 509.54263, 'epoch': 31} {'val_accuracy': 58.341076, 'time': 526.4424, 'epoch': 32} {'val_accuracy': 58.34728, 'time': 543.30194, 'epoch': 33} {'val_accuracy': 58.353485, 'time': 560.1487, 'epoch': 34} {'val_accuracy': 58.3612, 'time': 577.0582, 'epoch': 35} {'val_accuracy': 58.36808, 'time': 594.0279, 'epoch': 36} {'val_accuracy': 58.373608, 'time': 611.07294, 'epoch': 37} {'val_accuracy': 58.375286, 'time': 628.1597, 'epoch': 38} {'val_accuracy': 58.3778, 'time': 645.2522, 'epoch': 39} {'val_accuracy': 58.379982, 'time': 662.3246, 'epoch': 40} {'val_accuracy': 58.383003, 'time': 679.3447, 'epoch': 41} {'val_accuracy': 58.385017, 'time': 696.27783, 'epoch': 42} {'val_accuracy': 58.388203, 'time': 713.1839, 'epoch': 43} {'val_accuracy': 58.390717, 'time': 730.07983, 'epoch': 44} {'val_accuracy': 58.39256, 'time': 746.9867, 'epoch': 45} {'val_accuracy': 58.391724, 'time': 763.9096, 'epoch': 46} {'val_accuracy': 58.391724, 'time': 780.819, 'epoch': 47} {'val_accuracy': 58.391216, 'time': 797.7084, 'epoch': 48} {'val_accuracy': 58.39038, 'time': 814.5716, 'epoch': 49} {'val_accuracy': 58.39038, 'time': 814.57153, 'epoch': 50} {'val_accuracy': 58.39038, 'time': 814.5716, 'epoch': 51} INFO:syne_tune.blackbox_repository.simulated_tabular_backend:Trial 23: Fetching results: r=1, elapsed_time = 33.525 r=2, elapsed_time = 33.525 r=3, elapsed_time = 33.525 r=4, elapsed_time = 50.358 r=5, elapsed_time = 67.255 r=6, elapsed_time = 84.193 r=7, elapsed_time = 101.093 r=8, elapsed_time = 118.045 r=9, elapsed_time = 135.033 r=10, elapsed_time = 152.080 r=11, elapsed_time = 169.169 r=12, elapsed_time = 186.288 r=13, elapsed_time = 203.402 r=14, elapsed_time = 220.461 r=15, elapsed_time = 237.451 r=16, elapsed_time = 254.373 r=17, elapsed_time = 271.279 r=18, elapsed_time = 288.193 r=19, elapsed_time = 305.167 r=20, elapsed_time = 322.185 r=21, elapsed_time = 339.268 r=22, elapsed_time = 356.346 r=23, elapsed_time = 373.413 r=24, elapsed_time = 390.447 r=25, elapsed_time = 407.466 r=26, elapsed_time = 424.482 r=27, elapsed_time = 441.512 r=28, elapsed_time = 458.557 r=29, elapsed_time = 475.613 r=30, elapsed_time = 492.605 r=31, elapsed_time = 509.543 r=32, elapsed_time = 526.442 r=33, elapsed_time = 543.302 r=34, elapsed_time = 560.149 r=35, elapsed_time = 577.058 r=36, elapsed_time = 594.028 r=37, elapsed_time = 611.073 r=38, elapsed_time = 628.160 r=39, elapsed_time = 645.252 r=40, elapsed_time = 662.325 r=41, elapsed_time = 679.345 r=42, elapsed_time = 696.278 r=43, elapsed_time = 713.184 r=44, elapsed_time = 730.080 r=45, elapsed_time = 746.987 r=46, elapsed_time = 763.910 r=47, elapsed_time = 780.819 r=48, elapsed_time = 797.708 r=49, elapsed_time = 814.572 r=50, elapsed_time = 814.572 r=51, elapsed_time = 814.572

**Comment by mseeger** [comment]
Interestingly, for this record, the values are the same for r=1,2,3 and also for r=49,50,51.

**Comment by mseeger** [comment]
OK, I confirm Martin's observation that these errors are not in the raw data.

My best guess is this has something to do with the surrogate regression. This should really only be done with the config as input, so that a record (config1, resource1) can only be interpolated with data from the same resource level.

**Comment by mseeger** [comment]
This bug affects all lcbench blackboxes. Test code in branch `test_blackboxes`:

`pytest tst/blackbox_repository/test_data_consistency.py`

**Comment by mseeger** [comment]
@geoalgo Would be great if you could have a look at this.

**Comment by geoalgo** [comment]
This is because KNN nearest neighbor is used, if you use XGBoost or MLP as the regressor you will get different values. I propose to close it when Yahpo is integrated as it should address it.

**Comment by mseeger** [comment]
OK, I tried XGBoost, and this gives me even worse errors, like negative time per epoch:

`E       AssertionError: blackbox = lcbench, dataset = Fashion-MNIST, seed = None, config = {'num_layers': 2, 'max_units': 537, 'batch_size': 20, 'learning_rate': 0.0007077249235685832, 'weight_decay': 0.09981621075549935, 'momentum': 0.9351508741819156, 'max_dropout': 0.14136953900438576}
E         24:451.19171142578125 -> 25:443.4658508300781, 48:892.6231689453125 -> 49:888.5320434570312`

**Comment by mseeger** [comment]
And here with RandomForestRegressor:

`E       AssertionError: blackbox = lcbench, dataset = covertype, seed = None, config = {'num_layers': 2, 'max_units': 537, 'batch_size': 20, 'learning_rate': 0.0007077249235685832, 'weight_decay': 0.09981621075549935, 'momentum': 0.9351508741819156, 'max_dropout': 0.14136953900438576}
E         8:380.69561630249024 -> 9:367.29770767211915, 25:1020.4379803466796 -> 26:1006.0415319824219, 26:1006.0415319824219 -> 27:949.0156890869141`

**Comment by mseeger** [comment]
All of this would be easy to fix, if we just did not interpolate along resource, but only along config attributes. In that case, KNN would work by default, and so would be Random Forest, because the full learning curve is included in a leaf node.

**Comment by mseeger** [comment]
In any case, this is a bit scary to me (good luck only the LCBench BB uses surrogates), so I'd propose to find a solution to having a consistency test being run on the BB data as part of the CI.

**Comment by mseeger** [comment]
Aha OK, so when I choose KNN wth K=1, then my test goes through!

Makes sense. The default is K=5, and the docs say it somehow interpolates between the K NNs, so if that set is the same for several different resource levels, you get always the same values.

OK, so I will set the default to KNN with K=1, this should solve it for now.

Of course, once Yahpo is in there, maybe this is better. But we should test it then.

**Comment by mseeger** [comment]
Fixed by #333

**Comment by mseeger** [comment]
Using KNN with K=1 is not a great general solution.
Instead, we should use multioutput regression, as supported both in scikit-learn and XGBoost:

[sckit.learn](https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html#sklearn.multioutput.MultiOutputRegressor)
[xgboost](https://xgboost.readthedocs.io/en/stable/tutorials/multioutput.html)
