### ISSUE TITLE
ImportError for BotorchSearcher

### ISSUE THREAD

**Issue by mseeger** [awslabs/syne-tune#324]
Test (3.8) fails with:

`____________ ERROR collecting tst/schedulers/test_schedulers_api.py ____________
ImportError while importing test module '/home/runner/work/syne-tune/syne-tune/tst/schedulers/test_schedulers_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tst/schedulers/test_schedulers_api.py:47: in <module>
    from syne_tune.optimizer.schedulers.botorch.botorch_searcher import BotorchSearcher
syne_tune/optimizer/schedulers/botorch/botorch_searcher.py:18: in <module>
    from botorch.models import SingleTaskGP
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/__init__.py:7: in <module>
    from botorch import (
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/acquisition/__init__.py:7: in <module>
    from botorch.acquisition.acquisition import (
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/acquisition/acquisition.py:16: in <module>
    from botorch.models.model import Model
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/models/__init__.py:7: in <module>
    from botorch.models.approximate_gp import (
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/models/approximate_gp.py:35: in <module>
    from botorch.models.gpytorch import GPyTorchModel
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/models/gpytorch.py:23: in <module>
    from botorch.acquisition.objective import PosteriorTransform
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/acquisition/objective.py:18: in <module>
    from botorch.models.model import Model
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/models/model.py:24: in <module>
    from botorch.models.utils.assorted import fantasize as fantasize_flag
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/models/utils/__init__.py:7: in <module>
    from botorch.models.utils.assorted import (
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/botorch/models/utils/assorted.py:21: in <module>
    from gpytorch.utils.broadcasting import _mul_broadcast_shape
E   ImportError: cannot import name '_mul_broadcast_shape' from 'gpytorch.utils.broadcasting' (/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/gpytorch/utils/broadcasting.py)`

**Comment by mseeger** [comment]
Current fix (in my PR): Comment out BotorchSearcher in test_schedulers_api.py

**Comment by mseeger** [comment]
Quick fix for now: BotorchSearcher commented out in test_schedulers_api.py

**Comment by geoalgo** [comment]
Could you indicate how you got the error?
The error does not seem to appear in the CI: 
https://github.com/awslabs/syne-tune/pull/350

**Comment by mseeger** [comment]
It does not appear because BotorchSearcher is commented out in main. I commented it out because the CI was failing. The error you see above is copied from the CI output.

**Comment by mseeger** [comment]
OK, so now it seems to work. I don't know, maybe they fixed something on their side.
