### ISSUE TITLE
Can this architecture find hyperparameters for multi-algorithm in parallel?

### ISSUE THREAD

**Issue by WZFish** [awslabs/syne-tune#325]
I need to find different algorithms' hyperparameters in parallel, such as RF and XGboost. I tried ray.tune but if I parallel find two algorithms hyperparameters  it will mix and send error, It will apply xgb parameters to RF. So I want to know this architecture can solve this problem?

**Comment by aaronkl** [comment]
Can you elaborate a bit more on your use-case? Do you want to search jointly for the right algorithm and hyperparameters?

**Comment by WZFish** [comment]
the use-case is maybe there is one dataset, and I want to parallel find 5 algorithms hyperparameters, these 5 algorithms is independent each other.  It means I start 5 ray actors for 5 algorithms to find hyperparameters. Before when I use ray.tune to do it.    5 ray.tune will mix the hyperparam each other.

**Comment by aaronkl** [comment]
What you could do is to define one categorical hyperparameter that defines the algorithm. Then you define all hyperparameters for your algorithms. For example, it could look like this:

**Comment by aaronkl** [comment]
Feel free to reopen if there are further questions
