### ISSUE TITLE
YAHPO and our blackbox return different values for lcbench and different datasets

### ISSUE THREAD

**Issue by mseeger** [awslabs/syne-tune#371]
Branch: `yahpo_benchmarks`

This branch contains some refactoring which makes YAHPO fully functional.

After getting very different results on some experiments on lcbench, when using our blackbox (with 1-nn surrogate) and YAHPO, I wrote a simple comparison test: `tst/blackbox_repository/test_lcbench.py`.

This test shows that the values for relevant metrics are totally different.

**Comment by mseeger** [comment]
At this point, I have no good idea what is wrong here. I am careful comparing metric values at configs which are (according to our blackbox) evaluated exactly for lcbench. While YAHPO uses a surrogate, the values should not be totally off when the surrogate is evaluated at input locations.

A first guess is that datasets have been mixed up, either on our side or on YAHPO side?

**Comment by geoalgo** [comment]
The values of yahpo and 1-NN are expected to be different given that a MLP is fitted in the case of Yahpo.
