### ISSUE TITLE
YAHPO and our blackbox return different values for lcbench and fcnet

### ISSUE THREAD

**Issue by mseeger** [awslabs/syne-tune#372]
Reopening this one. DO NOT CLOSE THIS, IT IS NOT COMPLETE!

**Comment by mseeger** [comment]
Taken over from #371

**Comment by mseeger** [comment]
I extended the test to fcnet. There, the YAHPO values make no sense at all. They are constant, independent of config and resource level.

**Comment by mseeger** [comment]
Errors for lcbench are way to large to be explained by some MLP fitting. In any case, this is asking for values exactly at the configs where the data is sampled, so even an MLP should get this done.

**Comment by mseeger** [comment]
I am spending a lot of work debugging this code, and I'd really ask for that work to be taken seriously. Please do not close issues without even looking at the details. Thanks.

**Comment by mseeger** [comment]
For now, I strongly discourage anybody from using YAHPO benchmarks (or ours as well?), before this is not cleaned up and explained.

**Comment by mseeger** [comment]
I note that fcnet is not even mentioned in the YAHPO documentation, but it still seems to be in there. So maybe they did it in a hurry?

**Comment by geoalgo** [comment]
Let me answer with more details on why I closed the previous issue.

On LCBench, the average relative errors are as follow for the 20 configs you used in your test:

```
relative error for Fashion-MNIST: 0.02764213052322324
relative error for airlines: 0.03557896491397235
relative error for albert: 0.030647883043058273
relative error for covertype: 0.09737743704016621
relative error for christine: 0.020993541385371545
```

The errors are small and should be totally expected since Yahpo is fitting an MLP. We can never expects the MLP to predict perfectly those points without overfitting.

Regarding FCNet, YAHPO is also fitting an MLP however, I would not consider using YAHPO for this benchmark given that FCNET configurations are evaluated on a grid and hence data is not i.i.d. which may not ensure a very good surrogate fit (which is probably why they did not use this one in the paper).

**Comment by mseeger** [comment]
I extended the comparison test by also calling YAHPO API directly. This way, I figured that the previous errors for fcnet came from evaluations silently failing because BenchmarkSet was created with check=False.

But now, the fcnet values from YAHPO are very wrong, between 2000 and 15000 for valid_loss, which should have values below 1. The fcnet case needs more attention by YAHPO authors.

**Comment by mseeger** [comment]
One point which could explain the differences on lcbench. The original lcbench data has 52 fidelities. We (Martin and me) figured that the first and last of these are not useful. The first is for the untrained model. So we removed them in our import script.

For YAHPO, we get 52 fidelities, so it seems they did not remove anything before fitting their surrogate, and that may explain the differences.

**Comment by geoalgo** [comment]
@mseeger How do you get the 52 fidelities for YAHPO? I am getting only 51 so I assume that the first observation of lcbench (which corresponds to initialization) has been filtered out already.

Regarding the errors, dont you think the relative errors I gave above would be reasonable for a MLP?

**Comment by mseeger** [comment]
So my guess is they did not remove the first, and then fitting a model to that could indeed be quite off. We also had issues before removing first and last.

**Comment by mseeger** [comment]
One problem is, AFAIK, they train their surrogates on their side, and then serve them, so I cannot just retrain this.

I still like the design of your BB repository quite a bit better, because there I can influence how the surrogate model fitting is done.

**Comment by mseeger** [comment]
ON HOLD: Wait until YAHPO authors retrained their lcbench surrogate, can then redo comparisons.
