### ISSUE TITLE
__repr__ for the search domain objects

### ISSUE THREAD

**Issue by martinferianc** [awslabs/syne-tune#375]
Dear syne-tune team, thank you for a great library! 

A useful feature for the config space domains: E.g: `randint`: https://github.com/awslabs/syne-tune/blob/main/syne_tune/config_space.py#L1032 would be to define the`__repr__` function for the domain object that would, for example, display the lower and the upper bounds. This would be useful for logging of a particular search job on the user side to know how the config space was set for a given experiment.

**Comment by Vinayak-Kannan** [comment]
Hey! Is this something I can work on?

**Comment by mseeger** [comment]
This is already done. `randint`, `uniform`, `choice` are just functions. The classes of objects they create, all have `__repr__` implemented.

**Comment by mseeger** [comment]
I'll close this one, but if I missed something, please reopen

**Comment by martinferianc** [comment]
Dear @mseeger and @geoalgo  thank you for looking at this. I see what you mean but for some return objects it does not seem to be the case, please see: 

```
>>> print(syne_tune.__version__)
0.3.0
>>> from syne_tune.config_space import uniform, loguniform, choice
>>> print(uniform(0.001, 0.01))
<syne_tune.config_space.Float object at 0x1034462e0>
>>> print(loguniform(0.001, 0.01))
<syne_tune.config_space.Float object at 0x103446c10>
>>> print(choice([0.001, 0.01])) # For example choice seems to give a nice print
choice([0.001, 0.01])
```

**Comment by geoalgo** [comment]
Thanks a lot @martinferianc for providing a simple example.
@martinferianc do you want to work on this or do you prefer to let @Vinayak-Kannan do it?

Btw, given what Martin provided, it would be great to add unit-tests that checks that repr provides the expected string.

For sending the PR, there is a script to run to add license automatically and format the code, you can take a look at our [contributing guideline](https://github.com/awslabs/syne-tune/blob/main/CONTRIBUTING.md#contributing-via-pull-requests).

**Comment by mseeger** [comment]
Please have a look at the current main branch:
https://github.com/awslabs/syne-tune/blob/main/syne_tune/config_space.py#L392

We have not released this yet. In general, if you like to know whether something has been done, please check the main branch.

@martinferianc, @Vinayak-Kannan : I'll shortly put up some issues we'd love to work one of you on. Thanks a lot for your interest!

**Comment by geoalgo** [comment]
Indeed, thanks for the catch Matthias it is already done in mainline. 

That being said, there would still be lots of value in adding an unit-tests for the different cases which can also be a good first issue :-)
