### ISSUE TITLE
Implement arbitrary and/or connection for stopping criteria

### ISSUE THREAD

**Issue by mina-ghashami** [awslabs/syne-tune#401]
We allow stopping criteria to be  a list of conditions (e.g. max_wallclock_time=60, min_metric_value={"mean_loss": -6.0}, etc.). Currently, Syne-tune considers them as OR connected statement and stop the HPO when at least one of statement holds true. 
The goal of this issue is to implement an arbitrary and/or connection among stopping criteria list.

**Comment by geoalgo** [comment]
Thanks Mina! I am closing this one as I have not hear of someone else echoing the same need.

In case someone needs to combine multiple metrics together, one option is to define your own `StoppingCriterion` or directly use a lambda for arbitrary stopping conditions:

```python
tuner = Tuner(
    trial_backend=trial_backend,
    scheduler=BayesianOptimization(config_space, metric="merror", mode="min"),
    stop_criterion=lambda status: status.wallclock_time > 10 or status.num_trials_started < 5,
    n_workers=n_workers,
)
```
