### ISSUE TITLE
YAHPO download and upload issues

### ISSUE THREAD

**Issue by wistuba** [awslabs/syne-tune#404]
When loading the YAHPO benchmark for the first time, it is not downloading it automatically and therefore fails.

Manually calling `generate` will overcome this problem, however, the function does not upload the files to s3 (there is an issue with the folder structure, `yahpo-xgboost` vs `yahpo/xgboost`).

**Comment by mseeger** [comment]
This is odd, why do things work for me? I noted it does not seem to write stuff to S3, but also I am not sure it has to. David is the person to comment on this.

**Comment by wistuba** [comment]
Does it still work after `rm -rf ~/.blackbox-repository/yahpo*`?
The reason to upload it to S3 is to not download it from the public repos all the time. Besides that, for most other benchmarks the preprocessing takes quite a bit of time which we can avoid by saving the preprocessed version.
