### ISSUE TITLE
KeyError: 'st_tuner_time' in TensorboardCallback

### ISSUE THREAD

**Issue by Valavanca** [awslabs/syne-tune#410]
In a locally run experiment with TensorboardCallback, an error occurs in getting time(`ST_TUNER_TIME`).
I assume that it is enough to change the order of the following lines:
https://github.com/awslabs/syne-tune/blob/c5229561068d37d621d70719e4ded6c05b0f463b/syne_tune/tuner_callback.py#L197-L198

**Comment by aaronkl** [comment]
Hey thanks for the catch. Yes that should indeed fix it

**Comment by aaronkl** [comment]
addressed in #412
