### ISSUE TITLE
Reaching the best trained model checkpoint

### ISSUE THREAD

**Issue by ElifCerenGok** [awslabs/syne-tune#422]
Hi, 
In Ray Tune I can get the checkpoint value of the "best" trial like this:
```
result = tune.run(
        tune.with_parameters(train),
        resources_per_trial={"cpu": 12, "gpu": gpus_per_trial},
        config=config,
        num_samples=num_samples,
        search_alg=hyperopt_search,
        scheduler=scheduler)
```
```
best_trial = result.get_best_trial("accuracy", "max", "last")
best_checkpoint_dir = best_trial.checkpoint.value
```
Then, I can load the best checkpoint to my model like this:
```
model_state, optimizer_state = torch.load(os.path.join(best_checkpoint_dir, "checkpoint"))
my_model = Lenet5()
my_model.load_state_dict(model_state)
```
I couldn't understand how to do the exact same thing with Syne Tune. (I can not reach the best trained model)
Could you please help with this ?
Thank you so much :)

**Comment by mseeger** [comment]
Hello,
Syne Tune is agnostic to how checkpointing is implemented, in the sense that your training script has to implement it (there are helper functions for PyTorch models). For this reason, we also do not have a simple way of accessing individual checkpoints and load corresponding models.

If we standardized the way in which training scripts write/load checkpoints more (as apparently Ray Tune is doing), we could offer this functionality. For example, for a user with PyTorch models, if they use our provided functions to save/load checkpoints (and not some home-made code), we could do it.

However, some training scripts may not include checkpointing (our schedulers still work then), some may checkpoint not after every epoch, and previous checkpoints for a trial are overwritten by newer ones. I am therefore not sure it is great practice to assume that certain checkpoints written during HPO (for the purpose of pause and resume) are available later on.

Also, I'd recommend to retrain your best model on all data, including the validation data, in which case the HPO checkpoint is of no use.

**Comment by mseeger** [comment]
Hello, we have this request on our back-log, to write some docs on how to do what you like to do.

However, please note you will have to implement checkpointing (save to / load from local files) on your own in your training script. If you use PyTorch, we provide some helper functions, please check the docs. If you use Hugging Face, we have an example that includes checkpointing.

**Comment by ElifCerenGok** [comment]
Okay, I understand. Thank yo soo much for your reply :)

**Comment by geoalgo** [comment]
Hi @ElifCerenGok, we added an example let us know if it solves your use-case! :-)
