### ISSUE TITLE
TuningStatus output shows last metric value for trial, not best one

### ISSUE THREAD

**Issue by mseeger** [awslabs/syne-tune#452]
I noted that the TuningStatus output, which displays in regular intervals during tuning, prints the last metric value received for a trial, not the best one received (for training functions which report values after every epoch).

This can lead to a final output where the best metric value found overall is better than the value for the trial in the table, which I find confusing. Namely, when we determine the best config, we look over all data, not just over the last epoch for each trial.

**Comment by geoalgo** [comment]
The reason of this choice is that the table reports several metrics, not just the metric being tuned, and we don't know the mode for the other metrics. If we would display the best metric, we would need to ask the mode for all metrics reported to display them in the table.
