### ISSUE TITLE
feat: Add `py.typed` file to package so type annotations are exposed

### ISSUE THREAD

**Issue by ConnorBaker** [awslabs/syne-tune#471]
Hello all!

Would you be interested in adding a `py.typed` file to your package?

Per PEP-561 (https://peps.python.org/pep-0561/), library authors who want to support type-checking of their code must add a `py.typed` file to their package and include it as part of the package data so it's redistributed.

Doing so would allow downstream users of the library to benefit from the inline type annotations you have, freeing them of the need to create and maintain type stubs.

**Comment by wesk** [comment]
Thanks for flagging this @ConnorBaker , I'm looking into this. Also feel free to raise a PR directly if you have a recommended approach for the `py.typed` change.

On a related note, I also noticed that we don't currently run type-checking as part of our CI. I'll take a look at both things.

**Comment by wesk** [comment]
@ConnorBaker are you using [MyPy](http://mypy-lang.org/) for your project's downstream type checking? My hunch is that we have some work to do on the syne-tune side before we are ready to redistribute the type annotations.

**Comment by ConnorBaker** [comment]
Hi Wes!

I use both MyPy and [Pyright](https://github.com/microsoft/pyright) for my projects. Why two? They manage to catch different things! Pyright is, in my opinion, the more advanced of the two, being the first to add support for recursive types. It's also closely related to the type checker VS Code uses by default for Python, [Pylance](https://github.com/microsoft/pylance-release) (which is unfortunately closed-source).

I also run type checking as part of the CI, so if you wanted an idea of what it could look like for your project, I have two examples:

- https://github.com/ConnorBaker/hypothesis_torch_utils
- https://github.com/ConnorBaker/mfsr_utils

Those projects also have a `py.typed` file present, if that's helpful.

The problem matchers in the `.github` directory aren't necessary but are nice to have. If you're unfamiliar, [problem matchers](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md) are essentially regular expressions which you can run on portions of job outputs to get nice annotations in the web UI about errors or warnings without having to dig through the logs.

I'll keep that in mind about the PR!

**Comment by ConnorBaker** [comment]
@wesk any suggestions on the best way to handle adding type annotations? File-wise, it's going to touch a lot of the repository and make rebasing on top of new changes painful. That makes me think an incremental approach would be best.

I've got a branch where I've typed the majority of the `backend` module (well, mypy is still unhappy about a few things but it's close!). I saw there's a PR to refactor the estimator file in `backend` and it looks like it won't merge cleanly (though it should be easy enough to add types to).

Would you like pull requests targeted to the file-level or the module level? I think the module-level makes more sense, but I don't know how much makes sense for you all to review at a time.

Let me know your preferences!

**Comment by wesk** [comment]
Hi @ConnorBaker, I agree that an incremental approach would make sense. 

Regarding a file-level or module-level approach, what are the tradeoffs for the two approaches? 

Feel free to directly raise a PR if you already have something working (or close to it), and we can continue the conversation there as well.

**Comment by wesk** [comment]
We can re-open
