### ISSUE TITLE
Files seem to be corrupted (hash mismatch)

### ISSUE THREAD

**Issue by ArlindKadra** [awslabs/syne-tune#476]
Hello all,

I updated to the most recent library version and noticed an issue in using the benchmarks. I am getting the following: 
`Files seem to be corrupted (hash mismatch) `, which keeps persisting across multiple code reruns. The issue was fixed in PR #428 initially.

The hash is consistent between the calls, however, it seems not to match the hardcoded one and not to be the same between different operating systems. For example for PD1:

Hardcoded one in syne-tune:

`bd5b599179b1c5163d146a26dd2d559e5cb561f491ef48a22503e821651fd4d1`

On Windows (11) I get:

`f693fed481e344267c3a897eb8e629056e93304ee21e6e90955029c9804cdfda`

On Linux (CentOS 7.9) I get:

`ca162d81cacadb1e177ec319e65d68f812140bbc5864b0dceac28bbcca328a70`

I am able to overcome the problem by hardcoding the hash to my local specific value, but it seems the function that calculates the hash is not working as intended maybe, unless I am doing something wrong.

**Comment by ArlindKadra** [comment]
Seems to be related to #462.

**Comment by mseeger** [comment]
Correct, this is related to #462.

You can work around this by passing `ignore_hash=True` to `load_blackbox`. The default is False, we will probably switch this to True until this bug is fixed.

**Comment by ArlindKadra** [comment]
Thanks, that is faster than substituting the hash for all benchmarks.

**Comment by mseeger** [comment]
In the latest main, we deactivated hash checks. We'll work on fixing the checking, then turn the default back to True

**Comment by mseeger** [comment]
With checking being switched off, this becomes an enhancement.
