### ISSUE TITLE
Please clarify the relationship between syne-tune and ray:tune

### ISSUE THREAD

**Issue by gilinachum** [awslabs/syne-tune#50]
Please clarify in readme.txt - Can syne-tune wrap any ray:tune scheduler/searcher? Which ray:tune version is used?
Is PBT supported on the SageMaker backend?

**Comment by mseeger** [comment]
Hello, thanks for your interest in Syne Tune.

We can wrap any ray:tune scheduler/searcher which adheres to what is said in syne_tune/optimizer/schedulers/ray_scheduler.py. This is excluding such schedulers which make use of TrialRunner, as this is something deeply engrained in Ray, and we have different back-ends (which are altogether simpler).

Now, ray:tune PBT depends on TrialRunner, but we implemented our own version, check syne_tune/optimizer/schedulers/pbt.py and examples/launch_pbt.py. This version of PBT uses checkpointing. It should work on the sagemaker back-end.

Please do let us know if you into trouble.

**Comment by geoalgo** [comment]
Hi Gili,

To complement Matthias answer,
* all schedulers/searchers of Ray should work except PBT and Optuna. 
* we are testing our code with the [latest version](https://github.com/awslabs/syne-tune/blob/main/requirements-ray.txt) of ray
* PBT is not working at the moment with the SageMaker backend but we can add support for this.
