### ISSUE TITLE
Control SyneTune logging verbosity

### ISSUE THREAD

**Issue by 610v4nn1** [awslabs/syne-tune#564]
**Is your feature request related to a problem? Please describe.**
When using Renate with SyneTune the logs are cluttered with a large number of less-important information.
I did not find a way to control that such that only a minimal amount of information is logged (allowing users to focus on more important aspects logged by other libraries used in the training). If a solution already exists, it would be great to highlight it in the documentation.

**Describe the solution you'd like**
I would like to be able to log a minimal amount of information from Syne Tune. 
I can provide a list of the the information I would like to log if needed.

**Describe alternatives you've considered**
Renate is currently bypassing the Syne Tune logging in favor of its own

**Comment by mseeger** [comment]
You can specify the logging level, even for certain modules. You can also switch off status reporting (the big table).
One example for how to change the log level is in:
https://github.com/awslabs/syne-tune/blob/main/benchmarking/commons/hpo_main_common.py#L134

**Comment by mseeger** [comment]
If you want to get information out of Syne Tune during an experiment, we have a callback which is quite powerful. See example here:
https://syne-tune.readthedocs.io/en/latest/faq.html#how-do-i-append-additional-information-to-the-results-which-are-stored
