### ISSUE TITLE
Change default output folder for model checkpointing.

### ISSUE THREAD

**Issue by aaronkl** [awslabs/syne-tune#582]
**Is your feature request related to a problem? Please describe.**
When we run the local backend inside a SageMaker training job we upload the Syne Tune folder to S3 such that we can access results later. This also includes model checkpoints.  If we frequently store checkpoints for example with PBT, this can cause S3 errors. 

**Describe the solution you'd like**
We should allow to specify a different output folder for checkpoints than the Syne Tune default folder. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mseeger** [comment]
Thanks. This is something I will look at.

**Comment by mseeger** [comment]
Dealt with by #589

**Comment by mseeger** [comment]
Note this was already solved for `RemoteLauncher`, but was forgotten to port to `benchmarking`. PR #589 is fixing that
