### ISSUE TITLE
Wrong Usage of np.random.randint

### ISSUE THREAD

**Issue by Shi-Soul** [awslabs/syne-tune#610]
**Describe the bug**  
When I use this lib to do hyperparameter optimization with RandomSearch method, I found the eror:
` ValueError: high is out of bounds for int32 `
when running the code like this:
`scheduler = RandomSearch(
    config_space,
    metric=metric,
    mode=mode,
    points_to_evaluate=[initial_config],
    # random_seed=42,
)`

After tracing along the source code, I think this line of code (at `~syne_tune.optimizer.schedulers.searchers.optimizer.scheduler_searcher.TrialSchedulerWithSearcher`) may cause this bug:
`
    def __init__(self, config_space: Dict[str, Any], **kwargs):
        super().__init__(config_space)
        self._searcher_initialized = False
        # Generator for random seeds
        random_seed = kwargs.get("random_seed")
        if random_seed is None:
            random_seed = np.random.randint(0, 2**32)
        logger.info(f"Master random_seed = {random_seed}")
        self.random_seed_generator = RandomSeedGenerator(random_seed)
`
That is, `np.random.randint(0, 2**32)` is wrong, and `np.random.randint(0, 2**31)` may be suitable.
I think this is because numpy use different default data type, and int32 is used in this case, causing this problem not detected when developing.
I have tested `np.random.randint` with different parameters in my PC and a Linux server. It seems that in this Linux server, int64 is used by default, and hence `np.random.randint(0, 2**63)` is the largest feasible one. 

**Desktop (please complete the following information):**  
 - OS: Windows 10, Ubuntu 9.4.0
 - Syne Tune Version 0.4.1

**Comment by mseeger** [comment]
Thanks for this bug report! It was recently fixed (#608). For now, you'd need to install for source, but the fix will be incorporated in the next release.
