### ISSUE TITLE
Questions on benchmarking

### ISSUE THREAD

**Issue by joxixixi** [awslabs/syne-tune#633]
Hello!

Thanks for your excellent project. I am new to syne-tune so please forgive my stupid questions.

1. How to understand "real benchmarks"? I found `benchmarking.benchmark_definitions.real_benchmark_definitions` but had no idea what real benchmarks mean. What are the differences between real benchmarks and benchmarks that are not real?
2. Can you provide me specific examples of how to launch experiments on a local machine, on a specific real benchmark (using maybe Bayesian Optimization) and on a specific not real benchmark? 
3. I am not sure what `nursery` means in syne-tune.

Thanks in advance for your help.

**Comment by mseeger** [comment]
Hello, it is best if you look at this tutorial:
https://syne-tune.readthedocs.io/en/latest/tutorials/benchmarking/README.html

- We distinguish between "real" and surrogate (or tabulated) benchmarks. The difference is explained in the tutorial. Most HPO users will be concerned with real benchmarks, where every evaluation for a trial means that real computation (training) is needed
- `benchmarking/nursery` is for examples of benchmarking, where reviewing is not as serious. For example, things in `nursery` are not guaranteed to be kept up-2-date

**Comment by mseeger** [comment]
Note that we are about to include some plotting tools, which allow to visualize results obtained from many experiments. So stay tuned.

**Comment by joxixixi** [comment]
Thanks for your answers. :)
Looking forward to the plotting tools!

**Comment by piiiiiiie** [comment]
Hi. I have a question. Does syne-tune support traditional machine learning benchmarks running on a local machine (i.e. maybe local backend)? Thank you.

**Comment by mseeger** [comment]
Yes, you do not need to use AWS or SageMaker to use Syne Tune. You can also just run locally. I recommend you give it a try
