### ISSUE TITLE
RemoteLauncher corrupts requirements.txt when not ending with newline

### ISSUE THREAD

**Issue by ystein** [awslabs/syne-tune#730]
**Describe the bug**  
When using the remote launcher, `syne-tune[extra]` is automatically added to a user provided `requirements.txt` [here](https://github.com/awslabs/syne-tune/blob/254ad0708703245e51da0b113f1067a2da92039a/syne_tune/remote/remote_launcher.py#L207-L208). If `requirements.txt` does not end with a newline, `syne-tune[extra]` is however jumbled together with the last line in `requirements.txt`. I'm not sure whether it’s technically required to end `requirements.txt`  with newlines, but it would be nice to handle this case gracefully either way.

**To reproduce**  
1. Run a SyneTune evaluation using the `RemoteLauncher` and provide a non-empty `requirements.txt` that does not end with a newline
2. The evaluation fails since pip cannot install `<last requirements.txt line>syne-tune[extra]`

**Expected behavior**  
`syne-tune[extra]` is added as a new line in  `requirements.txt` [here](https://github.com/awslabs/syne-tune/blob/254ad0708703245e51da0b113f1067a2da92039a/syne_tune/remote/remote_launcher.py#L207-L208) and not just appended to the file

**Comment by mseeger** [comment]
`RemoteLauncher` is older code, we now recommend the code in `benchmarking/commons` to be used. In a forthcoming PR, we will move this code under `syne_tune`, so it does not require installation from sources.

**Comment by mseeger** [comment]
For example, `syne_tune[extra]` contains a lot of dependencies, many of which are not needed by most applications. The new code allows to configure the dependencies for remote launching.

**Comment by mseeger** [comment]
Would you want to try and fix this?
