### ISSUE TITLE
Hard to find default configurations for schedulers

### ISSUE THREAD

**Issue by amueller** [awslabs/syne-tune#776]
I'm running the ``MOBSTER`` scheduler and I find it hard to figure out what the default configuration is, say the reduction factor between rungs. There's several reasons for that:

- The docstring of ``MOBSTER`` doesn't actually explain all the options, but refers to ``HyperBandScheduler`` instead (and neither on the website nor in VSCode there's an easy way to jump to that). Maybe adding a ``see also`` link would be good or using some docstring replication logic to repeat all the kwargs docs? There might be some package that does that for you?

- Finding the API docs for ``MOBSTER`` or ``HyperBandScheduler`` on the website is hard. Some searching found [this](https://syne-tune.readthedocs.io/en/latest/_apidoc/syne_tune.optimizer.baselines.html#syne_tune.optimizer.baselines.MOBSTER) but there was also [this](https://syne-tune.readthedocs.io/en/latest/_apidoc/syne_tune.experiments.default_baselines.html#syne_tune.experiments.default_baselines.MOBSTER) less helpful page.
- There's no links to the docstrings in the tutorial: https://syne-tune.readthedocs.io/en/latest/tutorials/multifidelity/mf_async_model.html#asynchronous-mobster
- The code in the examples isn't clickable to jump to the docstrings. I think ``intersphinx`` is the right plugin for that?

Once I found [the documentation of the paramteters](https://syne-tune.readthedocs.io/en/latest/_apidoc/syne_tune.optimizer.schedulers.hyperband.html#syne_tune.optimizer.schedulers.hyperband.HyperbandScheduler) it was actually quite helpful. But still not sure how to easily reach it.

This might seem nitpicks but if you care about broader adoption of your awesome package, I think documentation and navigation of documentation are really important topics.

**Comment by mseeger** [comment]
Hello Andreas,
the docstring for `MOBSTER` contains links to `HyperbandScheduler` docstring, which work for me. But I can add some additional "see also" links, good point.
I can also add links to docstrings in the tutorial, this makes sense as well.

Thanks for the feedback.

**Comment by amueller** [comment]
Hey Matthias. Where do you view the ``MOBSTER`` docstring? Is it either of the links I shared above?

**Comment by mseeger** [comment]
Closed by #787
