### ISSUE TITLE
GP not robust to NaN metric

### ISSUE THREAD

**Issue by amueller** [awslabs/syne-tune#778]
I'm running MOBSTER with default parameters, and my model (for whatever reason) decided to produce ``np.inf``, which took down the tuning process.
In particular, in ``transform_state_to_data``, the normalization makes all the targets be ``NaN``. One option would be to exclude inf from the normalization, but then probably the GP chokes. Setting ``inf`` to the largest observed value might make sense? Another option would be excluding the sample.
Any thoughts?

**Comment by geoalgo** [comment]
Hi Andreas, thanks for flagging this it seems like a good suggestion, @mseeger is the main author of this code and may be able to help you.

**Comment by mseeger** [comment]
Closed with #788
