### ISSUE TITLE
Doc mismatch leads to ImportError: cannot import name 'report' ?

### ISSUE THREAD

**Issue by la-cruche** [awslabs/syne-tune#80]
Hi, 

I'm using Syne Tune from a SageMaker-managed EC2 instance (notebook instance)

As indicated [here,](https://github.com/awslabs/syne-tune#how-to-enable-tuning-and-tuning-script-conventions) I'm using this code in my backend script:
`from syne_tune.report import report`
which returns an `ImportError: cannot import name 'report'`

and when I look in `report.py` I can see a `Reporter` but no `report`

This [blog post](https://aws.amazon.com/blogs/machine-learning/run-distributed-hyperparameter-and-neural-architecture-tuning-jobs-with-syne-tune/) however proposes a different code:

```
from syne_tune.report import Reporter
report = Reporter()
```

Could the README be clarified?

(Note that I cannot check the version: `import syne_tune syne_tune.__version__` returns an `AttributeError: module 'syne_tune' has no attribute '__version__'`

thanks!

**Comment by geoalgo** [comment]
Thanks for reporting this mismatch, I will take a look now.
