### ISSUE TITLE
[Question] Multiple runs for same parameter values

### ISSUE THREAD

**Issue by austinmw** [awslabs/syne-tune#813]
Hi, I'm doing a simple grid search to check retrieval augmented generation (RAG) parameters. How can I set it so the grid search tries each combination of parameters K times instead of 1, to better understand variance?

**Comment by mseeger** [comment]
Hello, you can use `allow_duplicates=True` with `GridSearcher`. The searcher will then cycle through the grid multiple times. In this case, it will never stop returning configs. If you know the grid size, just query it K times grid size times.

```
from syne_tune.optimizer.baselines import GridSearch

scheduler = GridSearch(
   config_space,
   metric="...",
   search_options={"allow_duplicates": True},
)
```

**Comment by mseeger** [comment]
Let me know if this works for you

**Comment by austinmw** [comment]
Thanks! Where do you input the K * grid_size?

**Comment by mseeger** [comment]
You use `StoppingCriterion`. If your training script only reports once at the end, you use `max_num_evaluations`.

One thing: `GridSearcher` does not have a method to return the grid size it is using. You can use `len(scheduler.searcher.hp_values_combinations)` to obtain the grid size.

Also note the order of evaluation. The grid searcher will run through all grid configs, then start again.

**Comment by austinmw** [comment]
Thanks!!
