### ISSUE TITLE
How to set and get experiment name?

### ISSUE THREAD

**Issue by la-cruche** [awslabs/syne-tune#84]
Hi,

I see in the [blog](https://aws.amazon.com/blogs/machine-learning/run-distributed-hyperparameter-and-neural-architecture-tuning-jobs-with-syne-tune/) that one can query experiments by name, to access the metrics:

```python
from syne_tune.experiments import load_experiment
tuning_experiment = load_experiment("train-cifar100-2021-11-05-15-22-27-531")
tuning_experiment.plot()
```

How do we know and set an experiment name?

**Comment by geoalgo** [comment]
I am closing this issue, feel free to reopen if this did not answer your question.
