### ISSUE TITLE
Load torch model weights to GPU associated with a given trial

### ISSUE THREAD

**Issue by adavidho** [awslabs/syne-tune#851]
**Is your feature request related to a problem? Please describe.**
Hi Everyone,

I’m currently struggling a bit with syne-tune and was I might find some help here.
I am using the Python Backend with ASHA for tuning various torch models.
I want train the models on GPU. The syne-tune logs also print that they assign particular trials to the different GPUs, e.g. 
`17748 - INFO - *** Assigned GPU 6 to trial_id 14`.
However, the model weights are not on this device when I initialise them. 
Is there some way for me to access the GPU id the syne-tune trial is assigned to and use it to load the model to the right device (e.g. `model.to(torch.device(f"cuda:{get_trial_id()}")`) or is there another recommended way to handle this?

**Describe the solution you'd like**
A way to retrieve the trial device id.

**Comment by geoalgo** [comment]
Hi @adavidho , GPU are assigned by setting the environment variable `CUDA_VISIBLE_DEVICE` in [this line](https://github.com/awslabs/syne-tune/blob/main/syne_tune/backend/local_backend.py#L238).

This means that your code should work by just doing `model.to(torch.device("cuda"))`.

**Comment by adavidho** [comment]
Well that was easy enough. Thank you

**Comment by adavidho** [comment]
Well that was easy enough. Thank you
