### ISSUE TITLE
Is there a tuner.data() API?

### ISSUE THREAD

**Issue by la-cruche** [awslabs/syne-tune#86]
Hi,

When using Syne Tune, I'd like to be able to extract raw tuning data (parameters, metrics, timestamps) in a dataframe to analyze them. Is there something like a tuner.data() API? For example [Sagemaker HPO has the great tuner.analytics()](https://sagemaker.readthedocs.io/en/stable/api/training/tuner.html#sagemaker.tuner.HyperparameterTuner.analytics)

If this API doesn't exist I suggest to add it to the roadmap

**Comment by geoalgo** [comment]
Hi Olivier, 

After running any experiment, you can obtain a dataframe with raw tuning data (which contains parameters, metrics and timestamps) by doing the following:

```python
df = load_experiment("name-of-your-tuning-experiment").results
```
