### ISSUE TITLE
Is there a tuner.best_config() API?

### ISSUE THREAD

**Issue by la-cruche** [awslabs/syne-tune#87]
After a tuner.run() execution, I'd like to be able to programmatically get the best config, either from the tuner or from its data folder, eg:

`tuner.best_config()`

or

```
tuning_experiment = load_experiment("experiment-xxxxxxxx")
tuning_experiment.best_config()
```

Is there an API for this?
If no, I suggest to add it to the roadmap

**Comment by mseeger** [comment]
The raw data allows you to do that with a bit of Pandas. You can also ask what is the best config until a certain experiment time, etc etc.
When it comes to plotting and extracting infos from the results, there remains much to be done, but we are not yet sure how we'll do this exactly.

**Comment by geoalgo** [comment]
`best_config()` is not always defined, for instance when you have multiple objectives, there is not a single best solution. As such it is not clear whether we will implement this method since it is only defined in some cases.

**Comment by geoalgo** [comment]
Perhaps I was too fast to close this, one thing we do is to have such a method and throw an error when multiple metrics are defined.
