### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'scheduler'

### ISSUE THREAD

**Issue by la-cruche** [awslabs/syne-tune#97]
Hi,

I launched a Syne Tune experiment few hours ago (`experiment-2022-01-11-10-57-17-491`), then stopped it and launched another one. 

While experiment-2022-01-11-10-57-17-491 was running I could see its chart using 

```
from syne_tune.experiments import load_experiment

tuning_experiment = load_experiment("experiment-2022-01-11-10-57-17-491")
tuning_experiment.plot()
```

Now, when I'm doing it from the same machine, I get a :

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-0c0bfae5f6de> in <module>
      1 # metric over time
----> 2 tuning_experiment.plot()

~/anaconda3/envs/python3/lib/python3.6/site-packages/syne_tune/experiments.py in plot(self, **plt_kwargs)
     51         import matplotlib.pyplot as plt
     52 
---> 53         scheduler = self.tuner.scheduler
     54         metric = self.metric_name()
     55         df = self.results

AttributeError: 'NoneType' object has no attribute 'scheduler'
```

What is wrong? Can the graph be accessed only while the tuner is running?

**Comment by geoalgo** [comment]
No the tuner can be accessed any time while the experiment is running or after.

Can you confirm the file tuner.dill is still there in `~/syne-tune/{your-experiment}/`?

Can you still load the tuner and scheduler? (you may not anymore due to a code change or if files were removed)

```python
from pathlib import Path
from syne_tune.tuner import Tuner
path = Path("~/syne-tune/{your-experiment}").expanduser()
tuner = Tuner.load(path)
print(tuner.scheduler)
```

**Comment by mseeger** [comment]
Can we close this one?
